### ISSUE TITLE
SASL package needed on Debian Jessie

### ISSUE THREAD

**Issue by wombley** [major/ansible-mailgun#3]
On Debian Jessie, this role will product the following errors in the mail log when sending emails:

warning: SASL authentication failure: No worthy mechs found
delivery temporarily suspended: SASL authentication failed; cannot authenticate to server smtp.mailgun.org[23.22.131.222]: no mechanism available

This is due to the lack of the relevant sasl2 modules for secure connection to mailgun. To fix manually:

apt-get install libsasl2-modules
/etc/init.d/postfix restart

Or in Ansible after the Mailgun role:
```
- name: Install SASL modules for Mailgun (bug workaround)
  hosts: aws:offsite:legacy
  become: true
  tasks:
    - apt: name=libsasl2-modules state=present
    - service: name=postfix state=restarted
```
